### ISSUE TITLE
update

### ISSUE THREAD

**Issue by opcode-network** [tarantool/gentoo-overlay#40] opened 2020-10-08 14:02 UTC
hello

I'd like to upgrade to https://github.com/tarantool/queue/releases/tag/1.0.7
Can you please add it to the overlay?

Thank you!

**Comment by Totktonada** [comment] 2020-10-29 19:41
Duplicate of #37. I have added 1.10.7, 2.3.3, 2.4.2 and 2.5.1 in 838284dc8712857dbfba5918c3b434a9b287636d. I'll add October 2020 releases soon.

**Comment by Totktonada** [comment] 2020-10-29 19:41
Argh, it is about queue. Sorry, misread your message.

**Comment by Totktonada** [comment] 2020-10-29 20:06
Added `=dev-lua/queue-1.0.8`.

**Closed** 2020-10-29 20:05 UTC

**Comment by opcode-network** [comment] 2020-10-30 08:31
Thank you!
